sudo: required
services:
  - docker
  
before_install:
  - docker build -t shellnet/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shellnet/docker-react npm run test

deploy:
  provider: 'elasticbeanstalk'
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-273584788480'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY






